;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Tools",DevComment="")
+GameplayTagList=(Tag="Tools.Cutter",DevComment="")
+GameplayTagList=(Tag="Tools.Hammer",DevComment="")
+GameplayTagList=(Tag="Tools.Screwdriver",DevComment="")
+GameplayTagList=(Tag="Tools.Wrench",DevComment="")

